### ISSUE TITLE
cannot load such file -- semantic-ui-sass

### ISSUE THREAD

**Issue by MatheusRV** [doabit/semantic-ui-sass#117]
```
 compass install semantic-ui --trace
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring gem-wrappers-1.3.2 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.3.2
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
LoadError on line ["55"] of /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- semantic-ui-sass
  /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  /usr/lib/ruby/vendor_ruby/compass/configuration/data.rb:179:in `require'
  /mnt/c/Cloud/OneDrive/Dev/Descobridor/frontend/config.rb:3:in `get_binding'
  /usr/lib/ruby/vendor_ruby/compass/configuration/serialization.rb:24:in `eval'
  /usr/lib/ruby/vendor_ruby/compass/configuration/serialization.rb:24:in `parse_string'
  /usr/lib/ruby/vendor_ruby/compass/configuration/serialization.rb:15:in `block in _parse'
  /usr/lib/ruby/vendor_ruby/compass/configuration/serialization.rb:14:in `open'
  /usr/lib/ruby/vendor_ruby/compass/configuration/serialization.rb:14:in `_parse'
  /usr/lib/ruby/vendor_ruby/compass/configuration/file_data.rb:7:in `block in new_from_file'
  /usr/lib/ruby/vendor_ruby/compass/configuration/inheritance.rb:207:in `with_defaults'
  /usr/lib/ruby/vendor_ruby/compass/configuration/file_data.rb:6:in `new_from_file'
  /usr/lib/ruby/vendor_ruby/compass/configuration/helpers.rb:19:in `configuration_for'
  /usr/lib/ruby/vendor_ruby/compass/configuration/helpers.rb:69:in `add_project_configuration'
  /usr/lib/ruby/vendor_ruby/compass/commands/project_base.rb:37:in `add_project_configuration'
  /usr/lib/ruby/vendor_ruby/compass/commands/installer_command.rb:9:in `configure!'
  /usr/lib/ruby/vendor_ruby/compass/commands/project_base.rb:15:in `initialize'
  /usr/lib/ruby/vendor_ruby/compass/commands/stamp_pattern.rb:69:in `initialize'
  /usr/lib/ruby/vendor_ruby/compass/exec/sub_command_ui.rb:42:in `new'
  /usr/lib/ruby/vendor_ruby/compass/exec/sub_command_ui.rb:42:in `perform!'
  /usr/lib/ruby/vendor_ruby/compass/exec/sub_command_ui.rb:15:in `run!'
  /usr/bin/compass:30:in `block in <main>'
  /usr/bin/compass:44:in `<main>'
```

```
$ gem env
/home/turing/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/rubygems/commands/environment_command.rb:154: warning: Insecure world writable dir /home/turing/.rvm/gems/ruby-2.4.1/bin in PATH, mode 040777
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11
  - RUBY VERSION: 2.4.1 (2017-03-22 patchlevel 111) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/turing/.rvm/gems/ruby-2.4.1
  - USER INSTALLATION DIRECTORY: /home/turing/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /home/turing/.rvm/rubies/ruby-2.4.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/turing/.rvm/gems/ruby-2.4.1/bin
  - SPEC CACHE DIRECTORY: /home/turing/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/turing/.rvm/gems/ruby-2.4.1
     - /home/turing/.rvm/gems/ruby-2.4.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/turing/.rvm/gems/ruby-2.4.1/bin
     - /home/turing/.rvm/gems/ruby-2.4.1@global/bin
     - /home/turing/.rvm/rubies/ruby-2.4.1/bin
     - /home/turing/bin
     - /home/turing/.local/bin
     - /home/turing/.nvm/versions/node/v8.7.0/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64/compiler
     - /mnt/c/ProgramData/Oracle/Java/javapath_target_73688921
     - /mnt/c/WINDOWS/System32
     - /mnt/c/WINDOWS
     - /mnt/c/WINDOWS/System32/wbem
     - /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0
     - /mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
     - /mnt/c/Users/mathe/AppData/Roaming/nvm
     - /mnt/c/Program Files/OpenSSH/bin
     - /mnt/c/HashiCorp/Vagrant/bin
     - /mnt/c/WINDOWS/System32
     - /mnt/c/WINDOWS
     - /mnt/c/WINDOWS/System32/wbem
     - /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0
     - /mnt/c/Users/mathe/AppData/Local/Microsoft/WindowsApps
     - /mnt/c/Users/mathe/AppData/Roaming/nvm
     - /mnt/c/Users/mathe/AppData/Local/atom/bin
     - /mnt/c/Program Files/Mercurial
     - /mnt/c/Program Files (x86)/Nmap
     - /mnt/c/Users/mathe/AppData/Local/Microsoft/WindowsApps
     - /snap/bin
     - /home/turing/.rvm/bin
     - /home/turing/.rvm/bin
```
bundle env
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
fatal: Not a git repository (or any parent up to mount point /mnt/c)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
## Environment

```
Bundler   1.15.4
Rubygems  2.6.11
Ruby      2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
GEM_HOME  /home/turing/.rvm/gems/ruby-2.4.1
GEM_PATH  /home/turing/.rvm/gems/ruby-2.4.1:/home/turing/.rvm/gems/ruby-2.4.1@global
RVM       1.29.3 (latest)
Git       2.7.4
Platform  x86_64-linux
OpenSSL   OpenSSL 1.0.2g  1 Mar 2016
rubygems-bundler (1.4.4)
```

## Bundler settings

```
path
  Set for your local app (/mnt/c/Cloud/OneDrive/Dev/Descobridor/frontend/.bundle/config): "vendor/bundle"
disable_shared_gems
  Set for your local app (/mnt/c/Cloud/OneDrive/Dev/Descobridor/frontend/.bundle/config): true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gemspec
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    jekyll-theme-leap-day (0.1.0)
      jekyll (~> 3.5)
      jekyll-seo-tag (~> 2.0)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.5.2)
      public_suffix (>= 2.0.2, < 4.0)
    colorator (1.1.0)
    ffi (1.9.18)
    forwardable-extended (2.6.0)
    jekyll (3.6.0)
      addressable (~> 2.4)
      colorator (~> 1.0)
      jekyll-sass-converter (~> 1.0)
      jekyll-watch (~> 1.1)
      kramdown (~> 1.14)
      liquid (~> 4.0)
      mercenary (~> 0.3.3)
      pathutil (~> 0.9)
      rouge (>= 1.7, < 3)
      safe_yaml (~> 1.0)
    jekyll-sass-converter (1.5.0)
      sass (~> 3.4)
    jekyll-seo-tag (2.3.0)
      jekyll (~> 3.3)
    jekyll-watch (1.5.0)
      listen (~> 3.0, < 3.1)
    kramdown (1.15.0)
    liquid (4.0.0)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    mercenary (0.3.6)
    pathutil (0.16.0)
      forwardable-extended (~> 2.6)
    public_suffix (3.0.0)
    rb-fsevent (0.10.2)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    rouge (2.2.1)
    safe_yaml (1.0.4)
    sass (3.5.2)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)

PLATFORMS
  ruby

DEPENDENCIES
  jekyll-theme-leap-day!

BUNDLED WITH
   1.15.4
```

### jekyll-theme-leap-day.gemspec

```ruby
# encoding: utf-8

Gem::Specification.new do |s|
  s.name          = "jekyll-theme-leap-day"
  s.version       = "0.1.0"
  s.license       = "CC0-1.0"
  s.authors       = ["Matt Graham", "GitHub, Inc."]
  s.email         = ["opensource+jekyll-theme-leap-day@github.com"]
  s.homepage      = "https://github.com/pages-themes/leap-day"
  s.summary       = "Leap Day is a Jekyll theme for GitHub Pages"

  s.files         = `git ls-files -z`.split("\x0").select do |f|
    f.match(%r{^((_includes|_layouts|_sass|assets)/|(LICENSE|README)((\.(txt|md|markdown)|$)))}i)
  end

  s.platform      = Gem::Platform::RUBY
  s.add_runtime_dependency "jekyll", "~> 3.5"
  s.add_runtime_dependency "jekyll-seo-tag", "~> 2.0"
end
```

**Comment by doabit** [comment]
You should add  `require 'semantic-ui-sass'` to compass `config.rb` file. https://github.com/doabit/semantic-ui-sass#existing-project

**Comment by MatheusRV** [comment]
Yes, already in rb

```
require 'compass/import-once/activate'
# Require any additional compass plugins here.
require 'semantic-ui-sass'

# Set this to the root of your project when deployed:
http_path = "/"
css_dir = "assets/css"
sass_dir = "_sass"
images_dir = "assets/images"
javascripts_dir = "assets/js"

# You can select your preferred output style here (can be overridden via the command line):
# output_style = :expanded or :nested or :compact or :compressed

# To enable relative paths to assets via compass helper functions. Uncomment:
# relative_assets = true

# To disable debugging comments that display the original location of your selectors. Uncomment:
# line_comments = false


# If you prefer the indented syntax, you might want to regenerate this
# project again passing --syntax sass, or you can uncomment this:
# preferred_syntax = :sass
# and then run:
# sass-convert -R --from scss --to sass sass scss && rm -rf sass && mv scss sass

```

**Comment by doabit** [comment]
First, please run `gem install semantic-ui-sass`.
